//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS_Dumper.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAS_Dumper.Localization.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册失败 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterFailed {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ASFEBridge 注册成功 的本地化字符串。
        /// </summary>
        internal static string ASFEnhanceRegisterSuccess {
            get {
                return ResourceManager.GetString("ASFEnhanceRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 的本地化字符串。
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器人 {0} 读取AccessToken失败 的本地化字符串。
        /// </summary>
        internal static string FetchTokenFailure {
            get {
                return ResourceManager.GetString("FetchTokenFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ========================================== 的本地化字符串。
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用机器人 的本地化字符串。
        /// </summary>
        internal static string NoBotsAvilable {
            get {
                return ResourceManager.GetString("NoBotsAvilable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件作者: Chr_, 联系方式: chr@chrxw.com 的本地化字符串。
        /// </summary>
        internal static string PluginContact {
            get {
                return ResourceManager.GetString("PluginContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱发电: https://afdian.net/@chr233 的本地化字符串。
        /// </summary>
        internal static string PluginInfo {
            get {
                return ResourceManager.GetString("PluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐安装 ASFEnhance, 支持自动更新插件 的本地化字符串。
        /// </summary>
        internal static string PluginStandalongMode {
            get {
                return ResourceManager.GetString("PluginStandalongMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件状态: {0} 的本地化字符串。
        /// </summary>
        internal static string PluginState {
            get {
                return ResourceManager.GetString("PluginState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 版本 {1}.{2}.{3}.{4} 的本地化字符串。
        /// </summary>
        internal static string PluginVer {
            get {
                return ResourceManager.GetString("PluginVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置文件读取失败, 插件将不会运行 的本地化字符串。
        /// </summary>
        internal static string ReadConfigError {
            get {
                return ResourceManager.GetString("ReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAS添加机器人失败 {0} {1} 的本地化字符串。
        /// </summary>
        internal static string SASAddBotFailed {
            get {
                return ResourceManager.GetString("SASAddBotFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态码: {0} 返回值: {1} 的本地化字符串。
        /// </summary>
        internal static string SASFailed {
            get {
                return ResourceManager.GetString("SASFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAS汇报 {0} 个Bot, 成功 {1} 个, 失败 {2} 个 的本地化字符串。
        /// </summary>
        internal static string SASFeedStatus {
            get {
                return ResourceManager.GetString("SASFeedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动汇报了 {0} 个 Bot 的本地化字符串。
        /// </summary>
        internal static string SASManual {
            get {
                return ResourceManager.GetString("SASManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SAS连接性测试: {0} 的本地化字符串。
        /// </summary>
        internal static string SASTest {
            get {
                return ResourceManager.GetString("SASTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出Token失败 {0} 的本地化字符串。
        /// </summary>
        internal static string TokenDumpFailed {
            get {
                return ResourceManager.GetString("TokenDumpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token信息已保存至 {0} 的本地化字符串。
        /// </summary>
        internal static string TokenDumpSuccess {
            get {
                return ResourceManager.GetString("TokenDumpSuccess", resourceCulture);
            }
        }
    }
}
